### ADD
POST http://localhost:3000/api/expense
Content-Type: application/json

{
  "nm_brg": "Minyak Goreng Barco",
  "nm_supp": "Nabati Padang",
  "jml": 75,
  "hrg" : 75000,
  "stn" : "PCS",
  "tgl": "2026-10-08"
}

### GET DATA BY ID 
GET http://localhost:3000/api/expense/1

### DELETE DATA BY ID
DELETE http://localhost:3000/api/expense/3

### GET ALL DATA
GET http://localhost:3000/api/expense
